import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/Navbar/Header";
const inter = Inter({ subsets: ["latin"] });
import BottomNavigation from "./components/Mobile/BotNav";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <BottomNavigation/>
        </Providers>
      </body>
    </html>
  );
}
