import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/Navbar/Header";
const inter = Inter({ subsets: ["latin"] });
import BottomNavigation from "./components/Mobile/BotNav";
import AuthUser from "./middleware/user"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <AuthUser>

          {children}
          </AuthUser>
          <BottomNavigation className="pb-16"/>
        </Providers>
      </body>
    </html>
  );
}
