import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/Navbar/Header";
const inter = Inter({ subsets: ["latin"] });
import BottomNavigation from "./components/Mobile/BotNav";
export const metadata = {
  title: "PenaGuru SMKN7Baleendah",
  description: "Generated by Duivion FROM SMKN7Baleendah",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <BottomNavigation className="pb-16"/>
        </Providers>
      </body>
    </html>
  );
}
